version: '3.3'
services:
  ###################################
  # ELASTIC & KIBANA
  ###################################
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: umbracoaccelerator-elasticsearch
    restart: unless-stopped
    environment:
      - node.name=umbracoaccelerator-elasticsearch
      - cluster.name=umbracoaccelerator-elasticsearch-cluster
      - cluster.initial_master_nodes=umbracoaccelerator-elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1072M -Xmx1072M"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - network.host=_eth0_
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    volumes:
      - "esdata:/usr/share/elasticsearch/data"
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: umbracoaccelerator-kibana
    restart: unless-stopped
    ports:
      - 5601:5601
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    depends_on:
      - elasticsearch    
volumes:
  esdata:
    driver: local
